In [1]:
import polars as pl

In [2]:
DB_PATH = r"C:\Users\decim\AppData\Roaming\MetaQuotes\Terminal\3ECBA7B376E7B0171B098071238161DA\MQL4\Files\mt4_backtests.db"
stats = pl.read_database_uri("select * from model_stats", f"sqlite:///{DB_PATH}", engine='adbc')
stats

shape: (2_784, 8)
┌────────────┬──────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┐
│ model_stat ┆ model_id ┆ date_from  ┆ date_to    ┆ overall_st ┆ yearly_st ┆ monthly_s ┆ is_optimi │
│ s_id       ┆ ---      ┆ ---        ┆ ---        ┆ ats        ┆ ats       ┆ tats      ┆ zation    │
│ ---        ┆ i64      ┆ str        ┆ str        ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│ i64        ┆          ┆            ┆            ┆ str        ┆ str       ┆ str       ┆ i64       │
╞════════════╪══════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1          ┆ 1        ┆ 2017.01.02 ┆ 2021.12.31 ┆ {"balance" ┆ [{"2017": ┆ [{"2017-0 ┆ 0         │
│            ┆          ┆ 00:00:00   ┆ 20:00:00   ┆ : {"start_ ┆ {"balance ┆ 1-01":    ┆           │
│            ┆          ┆            ┆            ┆ balance":  ┆ ": {"star ┆ {"balance ┆           │
│            ┆          ┆            ┆            ┆ 10…        ┆ t_ba…     ┆ ": {"st…  ┆           │
│ 2          ┆ 2        ┆ 2017.01.02 ┆ 2021.12.31 ┆ {"balance" ┆ [{"2017": ┆ [{"2017-0 ┆ 1         │
│            ┆          ┆ 00:00:00   ┆ 20:00:00   ┆ : {"start_ ┆ {"balance ┆ 1-01":    ┆           │
│            ┆          ┆            ┆            ┆ balance":  ┆ ": {"star ┆ {"balance ┆           │
│            ┆          ┆            ┆            ┆ 10…        ┆ t_ba…     ┆ ": {"st…  ┆           │
│ 3          ┆ 3        ┆ 2017.01.02 ┆ 2021.12.31 ┆ {"balance" ┆ [{"2017": ┆ [{"2017-0 ┆ 1         │
│            ┆          ┆ 00:00:00   ┆ 20:00:00   ┆ : {"start_ ┆ {"balance ┆ 2-01":    ┆           │
│            ┆          ┆            ┆            ┆ balance":  ┆ ": {"star ┆ {"balance ┆           │
│            ┆          ┆            ┆            ┆ 10…        ┆ t_ba…     ┆ ": {"st…  ┆           │
│ 4          ┆ 4        ┆ 2017.01.02 ┆ 2021.12.31 ┆ {"balance" ┆ [{"2017": ┆ [{"2017-0 ┆ 1         │
│            ┆          ┆ 00:00:00   ┆ 20:00:00   ┆ : {"start_ ┆ {"balance ┆ 1-01":    ┆           │
│            ┆          ┆            ┆            ┆ balance":  ┆ ": {"star ┆ {"balance ┆           │
│            ┆          ┆            ┆            ┆ 10…        ┆ t_ba…     ┆ ": {"st…  ┆           │
│ 5          ┆ 5        ┆ 2017.01.02 ┆ 2021.12.31 ┆ {"balance" ┆ [{"2017": ┆ [{"2017-0 ┆ 1         │
│            ┆          ┆ 00:00:00   ┆ 20:00:00   ┆ : {"start_ ┆ {"balance ┆ 1-01":    ┆           │
│            ┆          ┆            ┆            ┆ balance":  ┆ ": {"star ┆ {"balance ┆           │
│            ┆          ┆            ┆            ┆ 10…        ┆ t_ba…     ┆ ": {"st…  ┆           │
│ …          ┆ …        ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2780       ┆ 2781     ┆ 2017.01.02 ┆ 2021.12.31 ┆ {"balance" ┆ [{"2017": ┆ [{"2017-0 ┆ 1         │
│            ┆          ┆ 00:00:00   ┆ 20:00:00   ┆ : {"start_ ┆ {"balance ┆ 1-01":    ┆           │
│            ┆          ┆            ┆            ┆ balance":  ┆ ": {"star ┆ {"balance ┆           │
│            ┆          ┆            ┆            ┆ 10…        ┆ t_ba…     ┆ ": {"st…  ┆           │
│ 2781       ┆ 2767     ┆ 2017.01.02 ┆ 2021.12.31 ┆ {"balance" ┆ [{"2017": ┆ [{"2017-0 ┆ 0         │
│            ┆          ┆ 00:00:00   ┆ 20:00:00   ┆ : {"start_ ┆ {"balance ┆ 1-01":    ┆           │
│            ┆          ┆            ┆            ┆ balance":  ┆ ": {"star ┆ {"balance ┆           │
│            ┆          ┆            ┆            ┆ 10…        ┆ t_ba…     ┆ ": {"st…  ┆           │
│ 2782       ┆ 2767     ┆ 2022.01.03 ┆ 2022.12.30 ┆ {"balance" ┆ [{"2022": ┆ [{"2022-0 ┆ 0         │
│            ┆          ┆ 01:00:00   ┆ 23:00:00   ┆ : {"start_ ┆ {"balance ┆ 1-01":    ┆           │
│            ┆          ┆            ┆            ┆ balance":  ┆ ": {"star ┆ {"balance ┆           │
│            ┆          ┆            ┆            ┆ 10…        ┆ t_ba…     ┆ ": {"st…  ┆           │
│ 2783       ┆ 2782     ┆ 2022.01.03 ┆ 2022.12.30 ┆ {"balance" ┆ [{"2022": ┆ [{"2022-0 ┆ 0         │
│            ┆          ┆ 01:00:00   ┆ 23:00:00   ┆ : {"start_ ┆ {"balance ┆ 1-01":    ┆           │
│            ┆          ┆            ┆            ┆ balance":  ┆ ": {"star ┆ {"balance ┆           │
│            ┆          ┆            ┆            ┆ 10…        ┆ t_ba…     ┆ ": {"st…  ┆           │
│ 2784       ┆ 2782     ┆ 2024.01.02 ┆ 2024.04.19 ┆ {"balance" ┆ [{"2024": ┆ [{"2024-0 ┆ 0         │
│            ┆          ┆ 00:00:00   ┆ 23:00:00   ┆ : {"start_ ┆ {"balance ┆ 1-01":    ┆           │
│            ┆          ┆            ┆            ┆ balance":  ┆ ": {"star ┆ {"balance ┆           │
│            ┆          ┆            ┆            ┆ 10…        ┆ t_ba…     ┆ ": {"st…  ┆           │
└────────────┴──────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┘

In [5]:
overall_stats = stats.select(
    pl.col("date_from").str.to_datetime(format="%Y.%m.%d %H:%M:%S"),
    pl.col("date_to").str.to_datetime(format="%Y.%m.%d %H:%M:%S"),
    pl.col("overall_stats")
)
overall_stats

shape: (2_784, 3)
┌─────────────────────┬─────────────────────┬───────────────────────────────────┐
│ date_from           ┆ date_to             ┆ overall_stats                     │
│ ---                 ┆ ---                 ┆ ---                               │
│ datetime[μs]        ┆ datetime[μs]        ┆ str                               │
╞═════════════════════╪═════════════════════╪═══════════════════════════════════╡
│ 2017-01-02 00:00:00 ┆ 2021-12-31 20:00:00 ┆ {"balance": {"start_balance": 10… │
│ 2017-01-02 00:00:00 ┆ 2021-12-31 20:00:00 ┆ {"balance": {"start_balance": 10… │
│ 2017-01-02 00:00:00 ┆ 2021-12-31 20:00:00 ┆ {"balance": {"start_balance": 10… │
│ 2017-01-02 00:00:00 ┆ 2021-12-31 20:00:00 ┆ {"balance": {"start_balance": 10… │
│ 2017-01-02 00:00:00 ┆ 2021-12-31 20:00:00 ┆ {"balance": {"start_balance": 10… │
│ …                   ┆ …                   ┆ …                                 │
│ 2017-01-02 00:00:00 ┆ 2021-12-31 20:00:00 ┆ {"balance": {"start_balance": 10… │
│ 2017-01-02 00:00:00 ┆ 2021-12-31 20:00:00 ┆ {"balance": {"start_balance": 10… │
│ 2022-01-03 01:00:00 ┆ 2022-12-30 23:00:00 ┆ {"balance": {"start_balance": 10… │
│ 2022-01-03 01:00:00 ┆ 2022-12-30 23:00:00 ┆ {"balance": {"start_balance": 10… │
│ 2024-01-02 00:00:00 ┆ 2024-04-19 23:00:00 ┆ {"balance": {"start_balance": 10… │
└─────────────────────┴─────────────────────┴───────────────────────────────────┘

In [6]:
overall_stats.unnest("overall_stats")

SchemaError: invalid series dtype: expected `Struct`, got `str`